###### <center><img src="norse_logo.png" class="r-stretch"/></center>
<h1 style="font-size: 260%; margin: 0;">Real-time neuromorphics with Norse</h1>
<center style="width: 44%;">
    <ul style="list-style-type:none; float: left;">
        <li><h2>Jens Egholm Pedersen</h2></li>
        <li><i class="fa fa-envelope"/> <tt>&lt;jeped@kth.se&gt;</tt></li>
        <li><i class="fa fa-twitter"/> @jensegholm</li>
        <li><i class="fa fa-home"/> https://neurocomputing.systems</li>
                                    </ul>
</center>
<center style="width: 52%; float: left; margin: 0 1em;">
    
<br/>
    <img src="ncs.png" style="height: 200px; float: left; margin: 0 .1em;";/>
    <img src="kth.png" style="height: 200px;float: left; margin: 0 .8em;";/> 
    <img src="hbp.png" style="height: 200px;float: left; margin: 0 .1em;"  ;/> 
</center>  

<center><img src="norse_logo.png" class="r-stretch"/></center>
<h1>Goal: Bring the success of machine learning to neuromorphics</h1>
<table style="font-size: 140%;">
    <tr class="fragment" style=" background-color: transparent;"><td style="text-align:right;">5'</td><td colspan=2>Numerical acceleration of biological simulations</td></tr>
    <tr class="fragment" style=" background-color: transparent;"><td style="text-align:right;">10'</td><td colspan=2>Neuromorphic engineering with Norse</td></tr>
    <tr class="fragment" style=" background-color: transparent;"><td style="text-align:right;vertical-align: top;">30'</td><td colspan=2>Demonstration of real-time applications
    <br/>
    <div style="margin-left: 20%;";>
        Event-based camera processing <br/>
        Closed-loop control systems
    </div>
    </td></tr>
</table>

# 1. Numerical acceleration of biological simulations

![](https://github.com/ncskth/norse-rl/raw/master/book/images/EnvAgentBrain.png)

## Neurons as dynamical systems

<br/>
<div style="float: left; width: 36%; margin-right: 1em;" class="fragment">
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Saltatory_Conduction.gif/1024px-Saltatory_Conduction.gif" style="height: 600px; vertical-align: center;"/>
<span class="small">
        
Source: [Wikipedia](https://en.wikipedia.org/wiki/Nervous_tissue#/media/File:Saltatory_Conduction.gif)
        
</span>
</div>


<div style="float:left; width: 60%; vertical-align: center;" class="fragment">
    <h3>Approximate models</h3>
    <br/>
Math: $
\dot{v} = \tau_{mem}(v_{leak} - v + i)
$
   
<br/>
    
<div class="fragment">
    
Python: `delta_v = tau * (v_leak - old_v + i)`

</div>
    
</div>

<br/>
<h1 class="fragment" style="text-align: center;">How do we simulate that in real-time?</h1>

## Neuromorphic hardware accelerators


<div style="width: 35%; float: left; padding-right: 2em;" class="fragment">
    <br/><br/>
<img src="chiptobrain.png" />
</div>

<div style="width: 63%; float:left; font-size: 120%;" class="fragment">
    
<br/>
Many exciting neuromorphic platforms in development. But...
<ul>
    <li class="fragment">No common interface or programming language</li>
    <li class="fragment">Many platforms does not allow training on-chip</li>
    <li class="fragment">Interoperability is difficult</li>
</ul>
</div>


## Contemporary accelerators for machine learning

<center style="vertical-align: middle; width: 40%; float: left;" class="fragment">
<img src="pytorch.png" style="width:400px;margin: 2em;">
<img src="tensorflow.png" style="width:300px; margin: 3em;">
<img src="jax.png" style="width:200px;margin: 2em;">
</center>

<center style="float: left; width: 50%;" class="fragment">

<h4>Evolution of the graphical processing unit (GPU)</h4>
<img src="gpu.gif" class="r-stretch" style="background: white; padding: 1em;"/>
    
<p style="text-align: center;">
Source: <a href="https://ieeexplore.ieee.org/document/9623445">Dally et al.: Evolution of the GPU, IEEE Micro 2021</a>
    </p>

</center>
    

# Can we exploit modern machine learning accelerators?

![](https://github.com/ncskth/norse-rl/raw/master/book/images/EnvAgentBrain.png)

<h1>Yes <span class="fragment">- and they are compatible with neuromorphic hardware</span></h1>

# An alliance between deep learning and neuromorphic hardware

<br/>
<div style="width: 35%; float: left;">
<img src="norsetochiptobrain.png" style="height: 60%;">
</div>


<div style="width: 60%; float:left; font-size: 120%;">
    <br/>
<ul>
    <li class="fragment">We virtualize biological computation</li>
    <li class="fragment">Train models on conventional hardware</li>
    <li class="fragment">Transfer models to neuromorphic hardware <br/><span class="fragment">(<a href="https://en.wikipedia.org/wiki/Meta_learning">Similar to meta-learning</a>)</span></li>
</ul>

</div>

<center><img src="norse_logo.png" class="r-stretch"/></center>

<h1>2. Neuromorphic engineering with Norse</h1>

<h2>Goal: Bring the success of machine learning to neuromorphics</h2>

<ol>
    <li class="fragment">Define biological neuron models</li>
    <li class="fragment">Simulate models in time</li>
    <li class="fragment">Accelerating our simulation</li>
</ol>

## 2.1 Defining biological neuron models

Math: $\dot{v} = \tau_{mem}(v_{leak} - v + i)$

Python: `delta_v = tau * (v_leak - old_v + i)`

In [1]:
import torch
import norse.torch as snn

`import norse.torch as snn
snn.LICell()`

In [2]:
snn.LICell()

LICell(p=LIParameters(tau_syn_inv=tensor(200.), tau_mem_inv=tensor(100.), v_leak=tensor(0.)), dt=0.001)

`snn.LIFCell()`

### Defining our data

Norse is built on PyTorch who works with **tensors**.

In [3]:
torch.tensor([0])

tensor([0])

`torch.tensor([0])`

* Can be any dimension

`data = torch.ones(10)`

In [6]:
torch.zeros(2, 2)

tensor([[0., 0.],
        [0., 0.]])

* Spikes are represented as `1`

In [7]:
torch.ones(8)

tensor([1., 1., 1., 1., 1., 1., 1., 1.])

`data = torch.ones(10)`

Could be anything: vectors, matrices (cameras), high-dimensional data such as EEG recordings, etc.

We can check the shape with `.shape`

### Applying our data to our model

We can now take our **data** (tensor) and apply it to our **model** (neuron dynamics).

In [14]:
data = torch.ones(1)
model = snn.LICell()
model(data)

(tensor([0.], grad_fn=<AddBackward0>),
 LIState(v=tensor([0.], grad_fn=<AddBackward0>), i=tensor([1.])))

`snn.LIFCell()(torch.ones(1))`

* Neurons are **stateful**.

In [16]:
output, state =model(data)
state

LIState(v=tensor([0.], grad_fn=<AddBackward0>), i=tensor([1.]))

`output_values, output_state = snn.LICell()(data)`

## Data and neuron state

<br/><br/>
<img src="state.png" style="width: 400px; float: left;" />

<img src="https://ncskth.github.io/norse-rl/_images/spikes.gif" style="float: left; margin: auto 1em;" class="fragment"/>

### Spiking models

In [17]:
snn.LIFCell()(torch.ones(1))

(tensor([0.], grad_fn=<CppNode<SuperFunction>>),
 LIFFeedForwardState(v=tensor([0.], grad_fn=<AddBackward0>), i=tensor([1.])))

`snn.LIFCell()(data)`

## 2.2 Simulating our model - in time

In [20]:
model = snn.LIFCell()
data = torch.ones(1)
state = None
for t in range(100):
    output, state = model(data, state)
    print(output)

tensor([0.], grad_fn=<CppNode<SuperFunction>>)
tensor([0.], grad_fn=<CppNode<SuperFunction>>)
tensor([0.], grad_fn=<CppNode<SuperFunction>>)
tensor([0.], grad_fn=<CppNode<SuperFunction>>)
tensor([0.], grad_fn=<CppNode<SuperFunction>>)
tensor([0.], grad_fn=<CppNode<SuperFunction>>)
tensor([1.], grad_fn=<CppNode<SuperFunction>>)
tensor([0.], grad_fn=<CppNode<SuperFunction>>)
tensor([0.], grad_fn=<CppNode<SuperFunction>>)
tensor([1.], grad_fn=<CppNode<SuperFunction>>)
tensor([0.], grad_fn=<CppNode<SuperFunction>>)
tensor([0.], grad_fn=<CppNode<SuperFunction>>)
tensor([1.], grad_fn=<CppNode<SuperFunction>>)
tensor([0.], grad_fn=<CppNode<SuperFunction>>)
tensor([0.], grad_fn=<CppNode<SuperFunction>>)
tensor([1.], grad_fn=<CppNode<SuperFunction>>)
tensor([0.], grad_fn=<CppNode<SuperFunction>>)
tensor([0.], grad_fn=<CppNode<SuperFunction>>)
tensor([1.], grad_fn=<CppNode<SuperFunction>>)
tensor([0.], grad_fn=<CppNode<SuperFunction>>)
tensor([0.], grad_fn=<CppNode<SuperFunction>>)
tensor([1.], 

```model = snn.LIFCell()
state = None
data = torch.tensor(1)
state = None
for t in range(100):
    model
```

### Using tensors with time

Assuming time-series data, we can simulate it all at once.

In [23]:
data = torch.ones(100, 1)
snn.LIF()(data)

(tensor([[0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [0.],
         [1.],
         [0.],
         [0.],
         [1.],
         [0.],
         [0.],
         [1.],
         [0.],
         [0.],
         [1.],
         [0.],
         [0.],
         [1.],
         [0.],
         [0.],
         [1.],
         [0.],
         [0.],
         [1.],
         [0.],
         [0.],
         [1.],
         [0.],
         [0.],
         [1.],
         [0.],
         [0.],
         [1.],
         [0.],
         [0.],
         [1.],
         [0.],
         [0.],
         [1.],
         [0.],
         [0.],
         [1.],
         [0.],
         [0.],
         [1.],
         [0.],
         [0.],
         [1.],
         [0.],
         [0.],
         [1.],
         [0.],
         [0.],
         [1.],
         [0.],
         [0.],
         [1.],
         [0.],
         [0.],
         [1.],
         [0.],
         [0.],
         [1.],
         [0.],
         [0.],
         [

```data = torch.ones(10, 1)
model = snn.LIF()
output, state = model(data)
output```

Note the difference between `LIFCell` (without time) and `LIF`.

PyTorch convention.

## 2.3 Accelerating our model

Our models have so far been running on the CPU - but it is simple to put them on the GPU.

In [24]:
model = snn.SequentialState(
  snn.Lift(torch.nn.Conv2d(1, 3, 5, padding=2)),
  snn.LIF(),
  torch.nn.Flatten(1),
  torch.nn.Linear(30000, 10),
  torch.nn.Sigmoid()
)
data = torch.ones(100, 1, 1, 100, 100)

```
model = snn.SequentialState(
    snn.Lift(torch.nn.Conv2d(1, 3, 5, padding=2)),
    snn.LIF(),
    torch.nn.Flatten(1),
    torch.nn.Linear(30000, 10),
    torch.nn.Sigmoid()
)
data = torch.ones(100, 1, 1, 100, 100)
```

* Notice how this **merges machine learning and biological** models.
  * This extends to complex biological phenomena such as plasticity and compartmental models
  * More available on https://norse.github.io/norse/

In [25]:
model = snn.SequentialState(
    snn.Lift(torch.nn.Conv2d(1, 3, 5, padding=2)),
    snn.LIF(),
    torch.nn.Flatten(1),
    torch.nn.Linear(30000, 10),
    torch.nn.Sigmoid()
).cuda()
data = torch.ones(100, 1, 1, 100, 100).cuda()

In [26]:
%timeit model(data)

15.4 ms ± 23.5 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)


%timeit model(torch.ones(100, 1, 1, 100, 100))

In [27]:
model = model.cpu()
data = data.cpu()

%timeit model(data)

36 ms ± 2.28 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


model = model.cuda()
data = data.cuda()

%timeit model(data)

## Norse performance
<br/>
<img src="benchmark_lif.png" style="height: 70%;"/>

# 3. Demonstration of real-time applications

<img class="fragment" src="https://github.com/ncskth/norse-rl/raw/master/book/images/EnvAgentBrain.png" style="width: 80%;"/>

1. Event-based camera processing
2. Closed-loop control systems

# 3.1 Event-based camera processing

Neuromorphic sensing is fundamentally different because they operate with **sparse** data.

Event-based cameras detect **luminosity <u>changes</u>** over time.

<img src="https://upload.wikimedia.org/wikipedia/commons/2/26/Event_camera_comparison.jpg" style="height: 400px;"/>
(Source: <a href="https://upload.wikimedia.org/wikipedia/commons/2/26/Event_camera_comparison.jpg">Wikipedia</a>)

## **Task**: Identify horizontal and vertical edges.

* Sparse: event-based - only when an event occurs => fast and low processing
* Frameless: high time resolution

* Other benefits: high dynamic range, low energy consumption, etc.

# 3.1 Event-based camera processing: edge detection

<br/>
<img src="2209_event_norse.png" style="width: 60%;"/>
<br/>

1. Connect to event-based camera in Python
2. Construct Norse model
3. Feed event-camera into Norse model

## 3.1.1 Connecting to an event-based camera in Python

We need an efficient tool: event cameras emit millions of events per second.

**Aestream** - address-event streaming library: https://github.com/norse/aestream

```python
import aestream
with aestream.DVSInput((640, 480)) as dvs:
    dvs.read() # Gives us a tensor
```

## 3.1.2 Construct Norse model

<br/>

Our model should

1. Detect either horizontal or vertical edges

2. Filter out noisy pixels

### A simple convolutional edge detector

By convolving our input signal with an edge detection kernel, we can single out oriented edges:

In [43]:
import matplotlib.pyplot as plt

kernel = (torch.linspace(-10, 10, 10).sigmoid().diff() - 0.14).repeat(9, 1)

```field = torch.linspace(-10, 10, 10).sigmoid().diff() - 0.14
kernel = field.repeat(9, 1)
plt.imshow(kernel)```

### Creating a convolutional PyTorch layer

In [45]:
kernels = torch.stack([kernel, kernel.T])
convolution = torch.nn.Conv2d(1, 2, 9)
convolution.weight = torch.nn.Parameter(kernels)

```kernels = torch.stack(kernel)
convolution = torch.nn.Conv2d(1, 2, 9)
convolution = torch.nn.Parameter(kernels)```

### Filtering out noisy pixels

How do we remove noise?

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Action_potential.svg/1280px-Action_potential.svg.png" style="height: 50%;"/>

(Source: <a href="https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Action_potential.svg/1280px-Action_potential.svg.png">Wikipedia</a>)

Can we use the refractory period?

### Modelling a simple noise filter with refractory neurons

In [46]:
noise_filter = snn.LIFRefracCell()

`noise_filter = snn.LIFRefracCell()`

### Putting it together: an edge detector in Norse


In [47]:
model = snn.SequentialState(
  noise_filter,
  convolution
)

```model = snn.SequentialState(
   noise_filter,
   convolution
)```

## 3.1.3 Feeding event-based camera into the model

<br/>
<img src="2209_event_norse.png" style="width: 60%;"/>
<br/>

In [ ]:
state = None
with aestream.DVSInput((640, 480)) as dvs:
    data = dvs.read()
    output, state = model(data, state)

```python

model = snn.SequentialState(
   noise_filter,
   convolution
)

with aestream.DVSInput((640, 480)) as dvs:
    # Read the data
    data = dvs.read()
    # Run the model (with the previous state)
    output, state = model(data, state)
```

# 3.1 Event-based edge detector with Norse and aestream

In [48]:
%%html
<div align="middle">
<video width="80%" controls autoplay loop>
      <source src="2209-edge-detection.mp4" type="video/mp4">
</video></div>

Full code is available online: [https://github.com/norse/aestream](https://github.com/norse/aestream/blob/main/example/usb_edgedetection.py)

# 3.2 Real-time neural control system with Norse

<br/>
<img src="https://github.com/ncskth/norse-rl/raw/master/book/images/EnvAgentBrain.png" style="width: 52%; float: left; margin: 0 2%;" class="fragment"/>

<div class="fragment" style="float: left; width: 42%;margin: -14px 1rem;">
<img src="https://upload.wikimedia.org/wikipedia/commons/3/38/Braitenberg_Vehicle_2ab.png" style="height: 290px;"/>

Braitenberg vehicle
    
(Source: [Wikipedia](https://upload.wikimedia.org/wikipedia/commons/3/38/Braitenberg_Vehicle_2ab.png) )
    
</div>

## The Durin robot

<div style="width: 40%; float: left;">
<br/>    
    
https://github.com/ncskth/durin
    
* Time-of-Flight (ToF) sensors
* Four omnidirectional wheels
    
</div>

<img src="https://github.com/ncskth/durin/blob/main/durin/durin_birdseye.jpg?raw=true" style="width: 30%; float: left;"/>

1. Read ToF sensor data
2. Construct a Norse model
3. Send ToF sensor data to the Norse model and forward motor output

## 3.2.1 Read ToF sensor data

<div style="width: 50%; float: left;">

Durin has 8 Time-of-Flight sensors, in an 8x8 array:
    
```python
from durin import DurinUI

with DurinUI("durin5.local") as durin:
    (obs, dvs, cmd) = durin.read()
    obs.tof # Tof sensor data
```

<div class="fragment">
    
    
```python
    left = obs.tof[1, 3, 3]
```
    
</div>
    

<div class="fragment">
    
    
```python
    right = obs.tof[6, 3, 3]
```
    
</div>
    
    

<div class="fragment">
    
    
```python
    data = torch.tensor([left, right])
```
    
</div>
    
</div>
    
    
<img src="2209 durin.png" style="width: 40%; float: left; margin-left: 6%;"/>

## 3.2.2 Construct a Norse model

<div class="fragment" style="float: left; width: 42%;margin: -14px 1rem;">
<img src="https://upload.wikimedia.org/wikipedia/commons/3/38/Braitenberg_Vehicle_2ab.png" style="height: 400px;"/>
    
(Source: [Wikipedia](https://upload.wikimedia.org/wikipedia/commons/3/38/Braitenberg_Vehicle_2ab.png) )

In [50]:
p = snn.LIParameters(tau_mem_inv=100)
network = snn.LICell(p)

```python
p = snn.LIParameters(tau_mem_inv=100)
network = snn.LICell(p)
```

## 3.2.3 Send ToF sensor data to the Norse model and forward motor output

<br/>

<img src="2209 durin.png" style="width: 300px; float: left; margin-right: 6%;"/>

<img src="state.png" style="width: 300px; float: left;" class="fragment"/>

In [ ]:
state = None
output, state = network(data, state)
left, right = output
command = MoveWheels(left, right, right, left)
durin(command)

```python
# Update the network with the input and read the output
output, network_state = network(input_tensor, network_state)
left, right = output # Unpack
#                    NE     NW     SW     SE
command = MoveWheels(left, right, right, left)
durin(command)  # Send the command to Durin
```

## 3.2.3 Putting it all together

```python
from durin import DurinUI

with DurinUI("durin5.local") as durin:
    # Extract tof sensor data
    (obs, dvs, cmd) = durin.read()
    left = obs.tof[1, 3, 3]
    right = obs.tof[6, 3, 3]
    data = torch.tensor([left, right])
```

```python
    # Update the network with the input and read the output
    output, network_state = network(data, network_state)
    left, right = output  # Separate left and right outputs
    command = MoveWheels(left, right, right, left)
    durin(command)  # Send the command to Durin
```

# 3.2 Real-time neural control system with Norse

In [51]:
%%html
<div align="middle">
<video width="80%" controls autoplay loop>
      <source src="2209-durin-braitenberg.mp4" type="video/mp4">
</video></div>

Full example available here: [https://github.com/ncskth/durin/](https://github.com/ncskth/durin/blob/main/examples/braitenberg.py)

# 4. Summary
<br/>
<img src="https://github.com/ncskth/norse-rl/raw/master/book/images/EnvAgentBrain.png" style="width: 50%; float: left; margin: 0 2%;" class="fragment"/>
<img src="norsetochiptobrain.png" style="width: 30%; float: center;" class="fragment">

# 4. Summary

1. Learned to simulate and accelerate models with Norse and PyTorch
2. Demonstrated event-based processing with Norse
3. Demonstrated real-time neural control systems with Norse

## Integration Norse with neuromorphic platforms


<div style="width: 60%; float: left;">
    
Work is ongoing to run Norse models on

* SpiNNaker
* BrainScales
    
<p class="fragment">
    <img src="ncs.png" style="height: 300px; float: left; margin: 0 1em;";/>
</p>
    
</div>


<img src="norsetochiptobrain.png" style="width: 30%; float: center;">

# 5. Future work

* Low-power, high time resolution neuromorphic control systems

* Gradient-based optimization of biological networks
  * That are portable to neuromorphic hardware
  

* Meta-learning with outer (evolution) and inner (plasticity) training

* NeoHebbian, local plasticity rules directly in Python

<center>
<img src="norse_logo.png" class="r-stretch" style="height:260px;"/>
</center>
<h1 style="font-size: 220%; margin: 0;">Real-time neuromorphics with Norse</h1>

<center style="width: 44%;">
    <ul style="list-style-type:none; float: left;">
        <li><h2>Jens Egholm Pedersen</h2></li>
        <li><i class="fa fa-envelope"/> <tt>&lt;jeped@kth.se&gt;</tt></li>
        <li><i class="fa fa-twitter"/> @jensegholm</li>
        <li><i class="fa fa-home"/> https://neurocomputing.systems</li>
                                    </ul>
</center>
<center style="width: 52%; float: left; margin: 0 1em;">
    
<br/>
    <img src="ncs.png" style="height: 200px; float: left; margin: 0 .1em;";/>
    <img src="kth.png" style="height: 200px;float: left; margin: 0 .8em;";/> 
    <img src="hbp.png" style="height: 200px;float: left; margin: 0 .1em;";/> 
</center>

<br style="clear: both;"/>
    
**Thank you!**
    
<ul style="margin-top: -0.5em;">
    <li>Christian Pehle and the BrainScales team at Heidelberg University.</li>
    <li>Jörg Conradt, Juan P. Romero B., and our students at Neurocomputing Systems lab, KTH Royal Institute of Technology.</li>
    <li>Luis Plana, Andrew Rowley, and the SpiNNaker team at Manchester University.</li>
    <li>Human Brain Project for funding this work.</li>
</ul>